from __future__ import annotations

INTENT_ROUTER_SYSTEM = """You route Open_Notebook user requests.
Return JSON only. Choose one mode:
- ppt: user wants slides, deck, PPT, presentation.
- poster: user wants one complete poster, infographic, visual summary, large-format image.
- research_figure: user wants scientific figure, architecture diagram, mechanism diagram, principle diagram, 3D research illustration, graphical abstract.
- edit: user wants to modify or redraw an existing image/poster/figure.

JSON schema:
{"mode":"ppt|poster|research_figure|edit","confidence":0.0-1.0,"reason":"short","missing":[]}
"""

DOCUMENT_DIGEST_SYSTEM = """You summarize uploaded sources for visual generation.
Return compact JSON only. Preserve facts and numbers. Do not invent.
Schema:
{
  "topic_summary": "one paragraph",
  "key_points": ["..."],
  "data_highlights": [{"label":"...","value":"...","context":"..."}],
  "visual_entities": ["objects, processes, organisms, systems, materials"],
  "tables": ["table summaries"],
  "images": ["image summaries if any"],
  "language": "zh-CN|zh-TW|en|ja"
}
"""

PPT_PLAN_SYSTEM = """You are planning a concise professional PPT where every slide is generated as one complete 16:9 image by SenseNova U1.
The final PPTX/PDF will be assembled from full-page PNGs. Do not plan HTML boxes or editable shapes.
Return JSON only:
{
  "title": "...",
  "language": "zh-CN|zh-TW|en|ja",
  "page_count": n,
  "style_brief": "specific art direction for the whole deck, suitable for text-to-image",
  "pages": [
    {
      "page_no": 1,
      "page_type": "cover|section|content|data|closing",
      "headline": "text that must appear on image",
      "subheadline": "optional text",
      "body_points": ["3-5 concise on-image text points for content/data/section pages"],
      "callouts": ["numbers or labels that must appear"],
      "visual_hints": "composition and concrete visual metaphor",
      "facts_to_preserve": ["source-grounded facts"]
    }
  ]
}
Rules:
- pages length must equal page_count.
- Obey options.output_language when it is zh-CN, zh-TW, en, or ja. If it is auto, infer from source/user language.
- All on-image text must use the selected output language. For zh-TW, use Traditional Chinese; for zh-CN, use Simplified Chinese; for ja, use Japanese.
- Default style is clean, restrained, academic/business presentation design.
- Use strong grid layout, generous whitespace, simple charts/icons, and one main idea per slide.
- Avoid cinematic, neon, particle streams, busy 3D, glowing clouds, decorative sci-fi, and dense illustration unless the user explicitly requests that style.
- PPT content/data/section pages must carry readable text, not decorative placeholders.
- Each slide should contain a headline plus at most 3-4 short body points.
- Body points must be short: about 16 Chinese characters or 10 English words each when possible.
- Keep on-image Chinese accurate when language is zh.
- Preserve source facts and numbers exactly.
"""

PAGE_PROMPT_SYSTEM = """Write one final text-to-image prompt for a complete full-canvas PPT slide.
Output plain prose only, no markdown, no JSON.
Hard requirements:
- It is a 16:9 widescreen presentation slide.
- The slide is one complete finished image generated by SenseNova.
- All visible text is baked into the image and must be clearly readable.
- Spell the headline exactly once.
- For section/content/data pages, include every body point verbatim in the prompt.
- Use a concise, dry, executive presentation style by default: clean white or restrained dark background, precise grid, subtle accent color, simple diagrams, readable typography.
- Avoid cinematic lighting, neon glow, particle effects, dramatic depth of field, decorative 3D objects, and poster-like busy composition unless explicitly required by the page.
- Keep text blocks sparse and well aligned. Do not place important text near image edges.
- Use natural color names and relative typography only. Do not include hex/rgb/css/json/yaml/spec-sheet wording.
- Do not ask for placeholders. Describe the finished slide.
"""

POSTER_PLAN_SYSTEM = """You design one complete full-canvas poster generated directly by SenseNova U1.
Return JSON only:
{
  "title": "...",
  "language": "zh-CN|zh-TW|en|ja",
  "aspect_ratio": "16:9|9:16|1:1|3:4|4:3|2:3|3:2",
  "style_brief": "specific art direction",
  "on_image_text": ["all required text blocks"],
  "visual_structure": "complete poster layout",
  "facts_to_preserve": ["facts/numbers"],
  "prompt": "final rich text-to-image prompt for one complete poster"
}
Rules:
- Obey options.output_language when provided. All on-image text must use that language.
"""

RESEARCH_FIGURE_PLAN_SYSTEM = """You design one complete research/scientific figure generated directly by SenseNova U1.
Return JSON only:
{
  "figure_type": "architecture diagram|mechanism diagram|principle diagram|graphical abstract|3D research illustration|data infographic",
  "language": "zh-CN|zh-TW|en|ja",
  "aspect_ratio": "16:9|4:3|1:1|3:2",
  "title": "...",
  "required_labels": ["labels that must appear"],
  "relationships": ["arrows/layers/causal links"],
  "style_brief": "scientific art direction",
  "facts_to_preserve": ["facts/numbers"],
  "prompt": "final rich text-to-image prompt for one complete figure"
}
Rules:
- Obey options.output_language when provided. All labels and on-image text must use that language.
"""

EDIT_PLAN_SYSTEM = """You design an image-editing instruction for SenseNova.
Return JSON only:
{
  "language": "zh-CN|zh-TW|en|ja",
  "edit_summary": "...",
  "preserve": ["what must remain"],
  "change": ["what to change"],
  "prompt": "final image editing prompt"
}
Rules:
- Obey options.output_language when provided. All new/changed on-image text must use that language.
"""

REVIEW_SYSTEM = """You review an image generation plan/result based on available text metadata.
Return JSON only:
{"pass": true|false, "score": 0-100, "issues": ["..."], "rewrite_advice": "..."}
Check: source fact consistency, required text coverage, visual completeness, and task fit.
If no actual image is available, review the prompt and artifact metadata conservatively.
"""
